FROM nginx:alpine

WORKDIR /app

EXPOSE 80

RUN mkdir ./logs
RUN mkdir ./www

COPY ./www ./www
COPY ./config/app.conf /etc/nginx/conf.d/default.conf

RUN chown -R nginx:nginx www
RUN chmod -R 755 www

CMD [ "nginx", "-g", "daemon off;" ]